### ISSUE TITLE
expirationSeconds checks

### ISSUE THREAD

**Issue by sftim** [postfinance/kubelet-csr-approver#10]
- (Implement and) document checks on the `.spec.expirationSeconds` field for a kubelet CertificateSigningRequest
   - for example, only allow certificates to be issued with a duration of 86400 seconds (24 hours) by default
   - maybe a command line option to allow issuing certificates that last longer than this?

**Comment by clementnuss** [comment]
Interesting suggestion, however before implementing it I'd like to understand whether this is common practice to have the `kubelet-serving` certificates set to expire after one day. [According to the K8s doc](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubelet-serving-certs), 
> By default, these serving certificate will expire after one year.

I couldn't find an option to configure the `expirationSeconds` field of `kubelet` certificate requested with `serverTLSBoostrap` option, so I'm not sure whether this is common practice or not. digging more into this, as it would permit to make sure certificate rotation will happen after a year

**Comment by sftim** [comment]
OK, how about a 367 day maximum for duration? (a year plus a day, even if it's a leap year)

**Comment by sftim** [comment]
The kubelet might not request a duration and instead leave that to the default signer to decide. Having this code available (on an opt in basis) would help the kubelet / kubeadm authors prepare to switch to having the kubelet request a specific duration.

**Comment by clementnuss** [comment]
have implemented this, there still misses the documentation.

I took the liberty to hardcode an upper limit on the maximum expiration time (368 days per default), users can then use an env variable to reduce that duration.
Any opinion on that? shouldn't I be doing that ?

**Comment by sftim** [comment]
> I took the liberty to hardcode an upper limit on the maximum expiration time (367 days per default), users can then use an env variable to reduce that duration.

Sounds good to me.
If I make time for it, I'll open a PR to update the docs.

**Comment by clementnuss** [comment]
https://github.com/postfinance/kubelet-csr-approver/blob/feat/expirationSec/README.md

I have already updated the documentation, can you quickly check whether it's clear for the user what is happening here?

**Comment by sftim** [comment]
Looks great. I think this is done!
