### ISSUE TITLE
Consider alternate image registry to Docker Hub

### ISSUE THREAD

**Issue by bjw-s** [postfinance/kubelet-csr-approver#133]
Since Docker Hub has been applying rate limits on image pulls for a while now, and their more recent move to scrap free teams I feel that Docker Hub is becoming more and more hostile towards the OSS/hobbyist community.

I would like to propose providing GitHub Container Registry as an alternative (or completely switching over to it) for the project.
Would you be open to this? 

Thank you for considering!

**Comment by clementnuss** [comment]
almost done! I you can already pull a `:dev` tag from ghcr.io normally:
```bash
docker pull ghcr.io/postfinance/kubelet-csr-approver:dev
```

I will make a new tag during this week, but I first want to improve our chart releasing process.

**Comment by clementnuss** [comment]
closing :)

https://github.com/postfinance/kubelet-csr-approver/pkgs/container/kubelet-csr-approver/81837168?tag=v1.0.0

**Comment by bjw-s** [comment]
That is awesome! Thanks you for doing this! 🙏
