### ISSUE TITLE
A flag to bypass DNS resolvabilty check

### ISSUE THREAD

**Issue by bychart** [postfinance/kubelet-csr-approver#15]
Hello! I'd really appreciate it if you'd add a flag to disable the DNS name resolvability validation.
RegExp alone is probably good enough for the testing needs in absence of properly configured DNS server.
![Screen Shot 2021-12-30 at 11 52 29 PM](https://user-images.githubusercontent.com/29703409/147806133-1225d44a-fd5c-430b-a04f-81eb5abb1e96.png)
 :)

**Comment by clementnuss** [comment]
Hi!

I will implement that next week, needs a bit of refactoring in the function that does these checks. will be configurable through env var or cmd-line flag !

👋🏻

**Comment by clementnuss** [comment]
Hi @bychart,

this should be fixed on dev/ and if you use the `:latest` tag for the csr-approver.
configuration can be changed either with cmdline flag : `--bypass-dns-resolution true` or
with an environment variable: `BYPASS_DNS_RESOLUTION=TRUE`

can you confirm that it works for you?
