### ISSUE TITLE
Some certificates remain in the approved state but not approved,issued.

### ISSUE THREAD

**Issue by luisvillalobossalgado1987** [postfinance/kubelet-csr-approver#160]
We have a Kubernetes integration with Datadog 7.44.0 on AWS EKS clusters, to monitor resources and performance of different applications. Everything was working fine in EKS version 1.23 and earlier. However, after upgrading one of the clusters (dev) to EKS version 1.24, the integration stopped working.

Upon investigation, we realized that the problem seemed to be with the certificates generated by Datadog. EKS does not recognize their origin, and as a result, the certificates are left in a "pending" state. Being a development environment, daily it is turned off at night and turned on in the morning, by doing this the integration with Datadog is lost, and the command kubectl get csr | awk '{print $1}' | xargs kubectl certificate approve to manually approve the certificates and restore the integration.

AWS in its documentation indicates that a driver must be developed in order to automate the approval of certificates.
https://docs.aws.amazon.com/eks/latest/userguide/cert-signing.html#csr-considerations

Kubernetes recommends in its documentation to use a ready-built controller.
Third party custom controllers can be used: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubelet-serving-certs

1. First Experimentation:
On the development ('dev') cluster, we had a node with a CSR in a 'Pending' state.

<img width="1207" alt="image" src="https://github.com/postfinance/kubelet-csr-approver/assets/72559915/97184cf2-e384-4801-a8eb-4c44a936f863">

Then when installing the driver, the certificate is approved and issued
<img width="1201" alt="image" src="https://github.com/postfinance/kubelet-csr-approver/assets/72559915/240a26b9-c331-4747-aafd-aab35ab0a62e">

<img width="1200" alt="image" src="https://github.com/postfinance/kubelet-csr-approver/assets/72559915/c74d5e2e-58de-4e47-a094-b05bec0dc1e7">

2. Second Experimentation:
However, if the kubelet-csr-approver controller is already installed on the 'dev' cluster and then a new node is added to the cluster, the controller is able to approve the CSR of the new node, but does not issue the corresponding certificate. In this case, the CSR remains in the 'Approved' state, but does not change to 'Approved, Issued', this causes the integration of the new node with datadog to be unsuccessful.

<img width="1202" alt="image" src="https://github.com/postfinance/kubelet-csr-approver/assets/72559915/5a963d90-d6bf-420e-bef5-a5d2cd5302e5">

We appreciate any help

**Comment by clementnuss** [comment]
salut @luisvillalobossalgado1987,

thanks for the detailed issue. could you provide the logs of the controller for the 2nd experimentation ? I'd like to make sure the certificate was actually approved (I doubt it).

Also from the EKS documentation, it seems that the when a CSR is in `Approved` state, it might still be that it hasn't been approved at all. If you could do a `kubectl describe csr csr-9swxh` it would help determine whether it was really approved or not.

Another point: `kubelet-csr-approver` only approves CSRs, it does not sign them.

Finally, I think your regex might be wrongly defined: can you try to remove the `system:node:` prefix in your regex ? so that it looks like:
```
providerRegex='^ip-.*\.us-west2...'
```

hoping it helps :)

**Comment by clementnuss** [comment]
hi @luisvillalobossalgado1987 !

any news ? if not I'll close this issue in a week

**Comment by clementnuss** [comment]
without further info, I'm closing this issue. feel free to reopen if needed !
