### ISSUE TITLE
extra arbitrary SANs after valid DNS name

### ISSUE THREAD

**Issue by avoidik** [postfinance/kubelet-csr-approver#17]
hey,

if my assumption is correct after I read the source code, it is possible to add extra SANs to request and only the first one will be verified, technically I can still add `auth.company.com` into the list of SANs per threat model, amirite?

cheers

**Comment by clementnuss** [comment]
hi,

thanks for having a look at the code 👍🏻 
I think [this portion of the `DNSCheck` function](https://github.com/postfinance/kubelet-csr-approver/blob/4a9a9ec6267e7852c978daebf12c5714434e86cb/internal/controller/regex_ip_checks.go#L19-L22) prevents that from happening, you might have missed it while reviewing the code ?

**Comment by avoidik** [comment]
Ah snap, missed it. Thanks, very useful project.
