### ISSUE TITLE
Solve "The SAN DNS Name could not be resolved" without bypassDnsResolution

### ISSUE THREAD

**Issue by EmyLIEUTAUD** [postfinance/kubelet-csr-approver#171]
Hi !

I would like to know if there is a solution to solve the problem "The SAN DNS Name could not be resolved" **without using the bypassDnsResolution argument**.<br>
This is my entire error : `certificate request was not signed: cannot watch on the certificate signing request: certificate signing request is denied, reason: kubelet-serving cert denied, message: CSR not complying with kubelet-csr-approver validation process. Reason: The SAN DNS Name could not be resolved, denying the CSR`

Thanks in advance !

**Comment by clementnuss** [comment]
Hi @EmyLIEUTAUD 

currently no, as I don't see why someone would want to keep using DNS resolution but wouldn't want to actually resolve DAN names. maybe you can help me understand what's your use case ?

or is it because you have several SAN DNS names, one of which cannot be resolved ?

**Comment by EmyLIEUTAUD** [comment]
Hi ! 

The error is solved only when I set the parameter bypassDnsResolution to true. But I don't want to use this parameter which introduce a security flaw. 
So I try to find another solution. I have several SAN DNS names but even when I set providerRegex, allowedDnsNames and providerIpPrefixex it doesn't work (always the same error).

Do you have any idea of what is going wrong ?

**Comment by clementnuss** [comment]
I think the issue arises because one of your SAN DNS name cannot be resolved by `kubelet-csr-approver` 

Have you checked that there are no _internal DNS_ or other strange DNS names in your CSR ?

Could you post your CSR here for me to have a look at it ? (after removing the sensible bits, of course)

**Comment by EmyLIEUTAUD** [comment]
Hello,

Yes the SAN DNS are internal.

**Comment by EmyLIEUTAUD** [comment]
Hi, 

If the DNS are internal, is there any risk in using the bypassDnsResolution argument? Otherwise, what parameters do I need to add for this to work?

**Comment by clementnuss** [comment]
if you have a solid `providerRegex` expression, I think you can safely bypass dns resolution..

The reason I built in the dns resolution feature was to make sure that it was only possible to create CSRs for domain names that were actually existing.

Now if you have a good regex, that also does a good amount of protection: in the end what we want to avoid is that a malicious actor, having gained access of a node, starts to emit CSR for domain names such as `google.ch`, `api.gke.google`, etc., as he/she could then use that certificate (which would be valid for some Kubernetes applications) to impersonate a real endpoint.

Now if your regex only permits the types of domain names that you know, you are safe.

There's no way to set any other parameter than `bypassDnsResolution` if your CSR SAN DNS name cannot be resolved, and I won't build this feature in, as I don't see any reasonable reason to do so.

Hoping this helps 😄

**Comment by EmyLIEUTAUD** [comment]
I will set a solid regex and use the bypassDnsResolution argument then. 

Thanks for your help and you responsiveness!
