### ISSUE TITLE
fix: invalid syntax in ServiceMonitor helm template

### ISSUE THREAD

**Issue by networkhermit** [postfinance/kubelet-csr-approver#172]
helm chart version: 1.0.3

I enabled the serviceMonitor in helm values:

```yaml
metrics:
  serviceMonitor:
    enabled: true
```

But when I upgrade the helm release it failed due to invalid syntax in servicemonitor template:

```text
Error from server (BadRequest): error when creating "servicemonitor.yaml": ServiceMonitor in version "v1" cannot be handled as a ServiceMonitor: strict decoding error: unknown field "spec.selector.app.kubernetes.io/instance", unknown field "spec.selector.app.kubernetes.io/name"
```

```text
The ServiceMonitor "release-name-kubelet-csr-approver" is invalid: spec.endpoints[0].port: Invalid value: "integer": spec.endpoints[0].port in body must be of type string: "integer"
```

**Comment by clementnuss** [comment]
good point! I'm not using ServiceMonitor myself so I didn't catch this error

**Comment by clementnuss** [comment]
can you test with the new Helm chart (`1.0.4`) that it works correctly ?

**Comment by networkhermit** [comment]
> can you test with the new Helm chart (`1.0.4`) that it works correctly ?

Helm chart 1.0.4 works. I can see the kubelet-csr-approver metrics from Prometheus console.

**Comment by clementnuss** [comment]
perfect, I just created a [new release!](https://github.com/postfinance/kubelet-csr-approver/releases/tag/v1.0.4)

thanks for your contribution 👍🏼
