### ISSUE TITLE
deploy/k8s/deployment.yaml wasn't updated

### ISSUE THREAD

**Issue by remram44** [postfinance/kubelet-csr-approver#178]
Grabbing `https://github.com/postfinance/kubelet-csr-approver/blob/v1.0.4/deploy/k8s/deployment.yaml` (note: `v1.0.4`) will run the image `postfinance/kubelet-csr-approver:v1.0.1`

**Comment by clementnuss** [comment]
good point. will try to think about a solution to have this automatically updated..

**Comment by clementnuss** [comment]
I took the easy approach of setting the tag to `latest`. I couldn't come up with a way of setting the image tag to be automatically the same as the git tag, and I prefer to have the image tag set to latest than to manually edit the file (and for sure forget at some point to do it).

If someone has a better idea, please let me know :)
