### ISSUE TITLE
Node DNS name validation issue

### ISSUE THREAD

**Issue by hadi2f244** [postfinance/kubelet-csr-approver#181]
In the Readme it is mentioned : 
`It is important to understand that the node DNS name needs to be resolvable for the kubelet-csr-approver to work properly. If this is an issue for you, please file an issue and I'll add a flag to disable this validation.`

For some situations like local clusters where there is no DNS server to map node to ip, this type of requirement makes CSR leave `Denied`.  So adding a related flag to disable this validation makes sense.

**Comment by clementnuss** [comment]
salut @hadi2f244 

I think the `--bypass-dns-resolution` option is what you're looking for. if that's the case, I should update the readme, as I might have written the part you cited before I implemented the `--bypass-dns-resolution` option
