### ISSUE TITLE
Feature: Add podLabels

### ISSUE THREAD

**Issue by spammads** [postfinance/kubelet-csr-approver#221]
Hi & thanks for the project.
I've seen it’s possible to set additional Annotations to pods via `podAnnotations`.
Would be great if this was also the case for labels – eg `podLabels`.
Thanks again for the work.

**Comment by clementnuss** [comment]
should be available with v1.0.7 helm chart. please test it and let me know if it works :)

**Comment by spammads** [comment]
Sorry for the late reply … life got in the way.
Tested it and it worked. Thanks for your work on this & the quick fix!
