### ISSUE TITLE
Setting BypassDNSResolution also skips regex checks

### ISSUE THREAD

**Issue by hrak** [postfinance/kubelet-csr-approver#247]
When BypassDNSResolution == true The `DNSCheck` function [seems to bail out ](https://github.com/postfinance/kubelet-csr-approver/blob/7a51b11ce01115f0b40f673fb37a0f5e5a748426/internal/controller/regex_ip_checks.go#L33) before iterating over the CSR DNSNames, completely skipping the regex checks too.

Shouldn't this flag only skip the `r.DNSResolver.LookupHost` step?

**Comment by clementnuss** [comment]
good catch, I think you are right. given the name of the flag this is not the intended behaviour.

I'll write a few test cases and fix the issue, thanks for raising an issue!
