### ISSUE TITLE
Is it possible to be in "just approve" mode?

### ISSUE THREAD

**Issue by qadet123** [postfinance/kubelet-csr-approver#293]
I mean can this deploy only approve matched  CSRs and ignore the rest, not deny them? So i can check these CSRs manually.
I know there is a `--ignore-non-system-node` , but it seems only affect CSRs with specific condition.

**Comment by clementnuss** [comment]
it's currently not possible, but that could be helpful, I agree.
I'll add a new flag in the coming days and create a new release 🙃

**Comment by clementnuss** [comment]
should be ready in v1.2.4 😉
