### ISSUE TITLE
Request for an enhancement to support K8's 1.18

### ISSUE THREAD

**Issue by yashwanth-mannem** [postfinance/kubelet-csr-approver#34]
Thanks for the custom controller to auto approve the csr's. The current functionality of the project doesn't support older version of K8's v 1.18) as it leverages /v1beta1 k8's `apis.` 

Therefore, I would like to request for an enhancement to optimize the current functionality to support `v1beta1 apis.`

**Comment by clementnuss** [comment]
Hi @yashwanth-mannem,

I'm sorry but I cannot invest time to support a K8s version that is almost 2 years old 😬 

As an alternative I would suggest that you turn to this older project, that to my knowledge does support K8s 1.18 but does less secure checks before delivering the certificates: https://github.com/kontena/kubelet-rubber-stamp

**Comment by yashwanth-mannem** [comment]
Thanks for your response.
________________________________
