### ISSUE TITLE
Add a nodeselector to make the deployment to run on the master nodes

### ISSUE THREAD

**Issue by jsalatiel** [postfinance/kubelet-csr-approver#47]
Hi, would it be possible to add a nodeselector to make the deployment to run on the master nodes just like Kubelet Rubber Stamp?
Thanks!

**Comment by clementnuss** [comment]
hi,
sure, if you use the helm chart to deploy `kubelet-csr-approver`, you can simply specify it in the `values.yaml` config file, or set it with the command line:

```bash
helm install .... --set nodeSelector='node-role.kubernetes.io/master: ""'
```

the node selector is defined here: https://github.com/postfinance/kubelet-csr-approver/blob/main/charts/kubelet-csr-approver/values.yaml#L61

if you have an issue with that, feel free to reopen the issue
