### ISSUE TITLE
Several completed and Container status Unknown pods

### ISSUE THREAD

**Issue by jsalatiel** [postfinance/kubelet-csr-approver#54]
Hi, for some odd reason I have several kubelet-csr-approver pods in not running state. This only happens for its deployment, all other deployments do not have this behaviour.

![image](https://user-images.githubusercontent.com/5522389/168290363-7db3db5a-402e-4aa0-ba36-f1605f4a644e.png)

Any idea what may be causing this ?

**Comment by clementnuss** [comment]
hi!

really strange, never observed that on my side, and the controller is running on quite a number of clusters now without issue.
can you give more details? is there a way to reproduce this behavior ?

also, can you describe one of the `Completed` and one of the `ContainerStatusUnkown` pods ?

**Comment by clementnuss** [comment]
without further input, I will close this issue.

if someone else is having this issue, please comment this issue and I'll try to investigate
