### ISSUE TITLE
Only enable on specific username prefix

### ISSUE THREAD

**Issue by jsmouret** [postfinance/kubelet-csr-approver#61]
Hello,

I am trying to use a chart called [stackgres](https://gitlab.com/ongresinc/stackgres) on the same cluster as kubelet-csr-approver, but it fails to install because kubelet-csr-approver automatically denies its certificate request.

Revelant log line:
```
2022-06-11T13:51:08.348Z        INFO    controller.certificatesigningrequest    controller/csr_controller.go:107        Denying kubelet-serving CSR. Reason:CSR Spec.Username is not prefixed with system:node: {"reconciler group": "certificates.k8s.io", "reconciler kind": "CertificateSigningRequest", "name": "stackgres-operator", "namespace": ""}
```

Would it possible to have an option to only process CSR with a given prefix, like `system:node:`, and leave others untreated as they may have a different usage pattern?

Thank you

**Comment by clementnuss** [comment]
Hi @jsmouret,

good point, I will address it this week 👍🏻

**Comment by clementnuss** [comment]
@jsmouret I have started working on this, could you send an example CSR ? with `kubectl get csr ... -o yaml` 
I'd like to make sure I permit bypassing such CSR correctly

**Comment by jsmouret** [comment]
Sorry I don't have the csr available but here are repo steps if that can help:

```
helm repo add stackgres-charts https://stackgres.io/downloads/stackgres-k8s/stackgres/helm
helm install --namespace stackgres stackgres-operator stackgres-charts/stackgres-operator 
```

Thanks a lot

**Comment by clementnuss** [comment]
I've created an image where you can ignore the username when it doesn't start with `system:node` under the following repo:tag:
`postfinance/kubelet-csr-approver:ignore-non-system-node`

can you test it in your setup and report whether it solves your issue ?
usage is documented here: https://github.com/postfinance/kubelet-csr-approver/tree/feat/ignore-non-system-node#parameters
