### ISSUE TITLE
Image Tags

### ISSUE THREAD

**Issue by yasintahaerol** [postfinance/kubelet-csr-approver#63]
Hey, I checked images on dockerhub but there is no tag information. I think a tag should exist to use a specific version in values.YAML. What can we do about it?

**Comment by clementnuss** [comment]
Hi, 

if you have a look at the tags list you might not see the `vX.Y.Z` tags, as there are also a lot of sha256 checksums for the tags.
however if you search for tags starting with `v0.` for example, you will see that tags are indeed published:

![image](https://user-images.githubusercontent.com/2116997/174541662-6d461ce8-abf8-4966-a245-986ef0fb6b14.png)

thanks for notifying, I'm happy to have double checked this :)
