### ISSUE TITLE
Denies when hostname is not the dns name

### ISSUE THREAD

**Issue by challapradyumna** [postfinance/kubelet-csr-approver#76]
We explicity change the hostname of the box to a different naming convention the certificates get rejected because of this reason. 

```
The SAN DNS Name in the x509 CSR is not prefixed by the node name (hostname)
```

**Comment by clementnuss** [comment]
Ok, never thought about that use case.

I will implement a new command line flag to toggle this check 👍🏼

**Comment by clementnuss** [comment]
hi @challapradyumna 👋🏻 
I've implemented a config flag that permits to bypass the `dns name is prefixed with the hostname` check.

can you try the following image and report whether it works for you ?
`postfinance/kubelet-csr-approver:bypass-hostname-check`
